apiVersion: federation/v1beta1
kind: Cluster
metadata:
  name: local
spec:
  serverAddressByClientCIDRs:
  - clientCIDR: "0.0.0.0/0"
    serverAddress: "123.456.789.1:8001"
  secretRef:
    name: local
